name: Create Release and Publish

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-24.04

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - "3306:3306"
        env:
          MARIADB_DATABASE: db
          MARIADB_ROOT_PASSWORD: example
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Set up sbt
      uses: sbt/setup-sbt@v1    
      
    - name: Run tests
      run: sbt test
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@e4e1a9718ebb2a76347e357b17740e98752b5c11

    - name: Extract version
      id: version
      run: |
        VERSION=$(grep -m 1 'version :=' build.sbt | cut -d'"' -f2)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build universal package
      run: sbt Universal/packageBin Universal/packageZipTarball

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.VERSION }}
        name: Release v${{ env.VERSION }}
        body: " env.NOTES "
        draft: true
        prerelease: false
        files: |
          target/universal/your-app-${{ env.VERSION }}.zip
          target/universal/your-app-${{ env.VERSION }}.tgz
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and publish Docker image
      run: sbt Docker/publish
      env:
        DOCKER_TAG: ${{ env.VERSION }}
