name: Create Release and Publish

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep -m 1 'version :=' build.sbt | cut -d'"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build universal package
        run: sbt Universal/packageBin Universal/packageZipTarball

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and publish Docker image
        run: sbt Docker/publish
        env:
          DOCKER_TAG: ${{ env.VERSION }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: " env.NOTES "
          draft: true
          prerelease: false
          files: |
            target/universal/your-app-${{ env.VERSION }}.zip
            target/universal/your-app-${{ env.VERSION }}.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
